services:
  frontend:
    build: ./frontend
    depends_on: 
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:8081"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
